### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by NJM1564** [Arcaratus/VirtualMachines#6]
I added Virtual Machines to the new minecraft FTB Pyramid modpack. And when I placed the axe gotten when you start the pack it crashed leaving the fallowing log.

https://pastebin.com/as7ELbJj

The crash was probably do to the axes indestructibility or inability to do damage to mods. I'd to further testing with other axes that might do that but my potato powered pc takes far to long to load the pack. :/

**Comment by Arcaratus** [comment]
There is a new version out now where this is fixed.
